// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xafymxperuxjxifytkji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhhZnlteHBlcnV4anhpZnl0a2ppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NDIwMzUsImV4cCI6MjA2ODIxODAzNX0.BKhMI3IeN8phfFzECJFVwhPU7bbb48zAFBYVm2x-RlI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});